set_property SRC_FILE_INFO {cfile:C:/Users/yoges/Risc-V-Data-Memory/Data-Memory.srcs/constrs_1/new/zybo_constraints.xdc rfile:../../../Data-Memory.srcs/constrs_1/new/zybo_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports rst_i]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports led_o]
